### PR TITLE
Codespace ishmaello scaling fortnight 66w9pqpr9vgfr697

### PR DESCRIPTION
**Pull request by Ishmaello**
Not yet reached target but still trying to understand with few command lines tested

### CODE REVIEW

**Comment by pratikspatil024** [comment]
Could you please explain what you are trying to do?
Closing this as it doesn't make sense right now. Feel free to reopen once you reach your target.

**Comment by Ishmaello** [comment]
There's too much to understand,all I'm trying to do is to get certainly sure of usage in VM including interaction, all transactions services,commands etc. As per holder whom started seeing blockchain on contract addresses created on sushi swap being staked and locked, their keys still have not been revealed or should say created I have only trying to operate then in Polygonscan. But then this contract addresses I had to follow them source codes leading me to github. Let's say all I'm trying to do whatever needs to done with them because I'm not even sure if I've been able to verify them correctly they still need security audit.my problem is that all my to have i lost to many external wallet accounts,trust wallet, metamask, associated with transactions I attempted. In Polygon communities some members took passphrases claiming they are helping yeah needed help very much fool me I gave them.now these contracts has VS code IDE beta check
Screenshot_20230512_104311_com gspace android addon arm32

**Comment by Ishmaello** [comment]
Note that contract I'm referring to are from wheelmillionaires spins tokens are withdrawn using trusted wallet smart contracts call but are not to reflect there until one reaches the community with scaling solutions they said but that trust wallet was lost too mybe 6 months ago and wallet I created and funded on metamask and trust had same problems

**Comment by Ishmaello** [comment]
One more thing during the creation of Contract at the beginning, APIs on Polygonscan were included I hope they can make use to solve issue

**Pull request closed without merging**
