### PR TITLE
Paginate governance vote queries to avoid result truncation

### PR DESCRIPTION
**Pull request by svenski123**
# Description
Querying governance votes for proposals not in the deposit or voting periods relies on a transaction search which currently uses a default page size of 30 and does not iterate past the first page, thus only the first thirty votes are ever returned.

This PR increases the query page size to 100 and implements pagination when querying votes for a proposal, capped at 10 pages maximum to mitigate possible unexpectedly large results sets. Given a maximum validator set size of 105 and allowing for some multiply submitted votes, 1,000 results should be more than adequate (10 pages * 100 results per page).

# Changes
- [X] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Changes only for a subset of nodes

# Nodes audience

Any node where the rest server or the heimdallcli tool is used to query governance.

# Checklist
- [ ] I have added at least 2 reviewer or the whole pos-v1 team
- [ ] I have added sufficient documentation in code
- [ ] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply

## Testing
- [ ] I have added unit tests
- [ ] I have added tests to CI
- [X] I have tested this code manually on local environment
- [ ] I have tested this code manually on remote devnet using express-cli
- [ ] I have tested this code manually on mumbai
- [ ] I have created new e2e tests into express-cli

### Manual tests

Run `heimdallcli query gov votes 12 --trust-node | grep -c node:` and observe that 83 votes are returned instead of 30.

### CODE REVIEW

**Review by VAIBHAVJINDAL3012 — APPROVED** [review]

**Review by marcello33 — APPROVED** [review]

**Comment by marcello33** [comment]
Hey @svenski123 changes LGTM but `defaultLimit` is not consistent anymore with the value defined in `tendermint` (see [here](https://github.com/maticnetwork/tendermint/blob/peppermint/rpc/core/pipe.go#L22), as per comment.
Can you make sure it does? I'd leave the default values as currently defined, and implement pagination on top of them.
Thank you

**Comment by marcello33** [comment]
Also, @svenski123 can you add some unit/e2e tests to make sure pagination works as expected? Thanks

**Comment by temaniarpit27** [comment]
@svenski123 Please refer to the comments by developers and update so that we can review the PR

**Comment by temaniarpit27** [comment]
Closing this for now as no response in last 3 months. Please feel free to reopen once comments are resolved

**Pull request closed without merging**
