### PR TITLE
Allow Heimdall to be configured using env vars

### PR DESCRIPTION
**Pull request by victorcoder**
Thanks to viper we can setup the automatic env configuration, this is very convenient for running in docker as we don't need to add explicit params to the CLI and we avoid having to sed on config files.

### CODE REVIEW

**Comment by ferranbt** [comment]
Looks good. Though we are still limited because we do not have flags for many of the fields, only the one that points to the config file.

**Comment by victorcoder** [comment]
> Looks good. Though we are still limited because we do not have flags for many of the fields, only the one that points to the config file.

@ferranbt yes, but I'm currently looking to try to start up using docker/compose, without touching any config file at startup time, making the UX as simple as `docker-compose up` while we maintain rabbitmq and without compose when we get rid of it.

So for the first goal it works.

**Comment by ferranbt** [comment]
> So for the first goal it works.

Cool!

**Review by ferranbt — APPROVED** [review]

**Comment by victorcoder** [comment]
Checked and working well

**Pull request merged**
